# Generated by Django 5.0.2 on 2024-03-03 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='datas',
        ),
    ]
