# Generated by Django 5.0.2 on 2024-03-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0002_rename_data_datas'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('text', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='datas',
        ),
    ]
