# Generated by Django 5.0.2 on 2024-03-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audition', '0003_data_delete_datas'),
    ]

    operations = [
        migrations.CreateModel(
            name='mydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('roll', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=20)),
                ('phone', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='data',
        ),
    ]
